project:
  type: website
  output-dir: docs
  preview: 
    port: 4005
    browser: true

execute:
  freeze: auto

website:
  title: "Portfolio"
  site-url: "https://sachinverma.github.io/" # makes site links work on your remote site
  favicon: "resources/img/data-scientist-icon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: tutorials.qmd
        text: Tutorials
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: resume.qmd
        text: Resume
      - href: about.qmd

    right:
      - text: "{{< fa envelope size=large >}}"
        href: mailto:verma.sachin.ds@gmail.com
      - text: "{{< fa brands linkedin-in size=large >}}"
        href: https://linkedin.com/in/vermasachinds/
      - text: "{{< fa brands instagram size=large >}}"
        href: https://www.instagram.com/sachin.the.11_11/
      - text: "{{< fa brands github size=large >}}"
        href: https://www.github.com/koushikkhan/

format:
  html:
    theme:
      - default
      - styles/styles.scss
    html-math-method: katex
    mermaid: 
      theme: default
    toc: true
    code-block-bg: true
    code-block-border-left: true
    highlight-style: atom-one
    code-line-numbers: true
