---
title: "Projects"
from: markdown+emoji
resources:
  - .nojekyll
---

Presented here are personal projects I've undertaken while exploring diverse topics. I look forward to pursuing many more in the future.

+ Masters Thesis: Joint Modelling of Longitudinal and Time-to-event data - [Thesis](/resources/pdf/thesis/joint_modeling_thesis.pdf), [Slide](/resources/pdf/thesis/joint_modelling_final_presentation.pdf), [Data](/resources/pdf/thesis/DMD.csv)

+ Development of my Portfolio [web development, technical writing] - [GitHub](https://github.com/koushikkhan/koushikkhan.github.io/portfolio/)

+ Writing gradient descent from scratch [computing, python] - [GitHub](https://github.com/koushikkhan/The-Gradient-Descent-Optimization)

+ A simple pipeline to package & deploy a machine learning app [ml, deployment, docker] - [GitHub](https://github.com/koushikkhan/flask-ml-service)

+ Automating the boring stuffs after installing a linux distro [linux, shellscript] - [GitHub](https://github.com/koushikkhan/configure-my-linux)

+ A not so short introduction to object oriented programming using R [technical writing] - [Medium](https://medium.com/@koushikkhan38/a-not-so-short-introduction-to-object-oriented-programming-using-r-cd69d732f60?source=friends_link&sk=b65284c634367fc8627815c552777b5a)

+ Stock price forecasting with LSTM network [forecasting, deep learning] - [Colab](https://colab.research.google.com/drive/1xLgCoQF79MD61Ck45TEbWW9UtyymZGkF?usp=sharing)

+ Playing with word2vec [neural net, embedding] - [Colab](https://colab.research.google.com/drive/1PJCyPULfcYcsUpkvPeQsu4GNsp5m3b3v?usp=sharing)

+ A simple automation plan for time series forecasting: from data acquisition to model building and making forecast [time series, automation, rest api] - [GitHub](https://github.com/koushikkhan/automated-forecasting-pipeline)