---
title: "Skills and Expertises"
from: markdown+emoji
resources:
  - .nojekyll
---

Throughout my career journey, I've engaged in numerous projects, not all of which are noteworthy. Here, I've curated a selection of key projects, showcasing the tools and methodologies employed.

## {{< fa briefcase >}} S&P Global Inc. (2021-Present)
+ Development of data driven products for maritime supply chain
    + {{< fa screwdriver-wrench >}} Tools
        + Python, PySpark, Polars 
        + Excel and PowerBI (for reporting)
        + Amazon AWS
        
+ Forecasting green house gas (GHG) emission from ships with the help of shipping data
    + {{< fa screwdriver-wrench >}} Tools
        + Python, R, PySpark, Polars
        + Excel and PowerBI (for reporting)
        + Amazon AWS

+ Building data pipelines in Azure DevOps
    + {{< fa screwdriver-wrench >}} Tools
        + R, Python, PySpark, Polars
        + Microsoft Azure as DevOps platform

## {{< fa briefcase >}} IBM India Pvt. Ltd. (2016-2021)
+ Analysing customer complaints (a.k.a tickets) from various sources and predicting root causes using clustering and text classification respectively
    + {{< fa screwdriver-wrench >}} Tools
        + Machine Learning
        + Python
        + SQL
        + ShellScript
        + Python Flask (for developing REST API)
        + Docker, Kubernetes (for deployment)

+ Serving search queries to customers by designing a small scale search engine built on customer Feedbacks and FAQs using information retrieval algorithm
    + {{< fa screwdriver-wrench >}} Tools
        + Singular value decomposition 
        + Python, Pandas and Numpy

+ Understanding the effects of various factors like advertisement, promotion, weather on sales of several commodities, analysing ROI year-on-year basis and forecasting the furure sales using Marketing Mix Modeling
    + {{< fa screwdriver-wrench >}} Tools
        + Sales and ad data
        + Regression Techniques
        + R, Dplyr
        + SQL

## {{< fa briefcase >}} BCausE Enterprise Pvt. Ltd. (2015-2016)
+ Development of customer segmentation model
    + {{< fa screwdriver-wrench >}} Tools
        + Clustering
        + Python
        + MongoDB
        + Python Flask (for developing REST API)

+ Development of web scraping tools
    + {{< fa screwdriver-wrench >}} Tools
        + Python
        + Object Oriented Programming
        + BeautifulSoup (for web scraping)

## {{< fa building-columns >}} Academics
+ Digitization of class notes, preparation of project reports
    + {{< fa screwdriver-wrench >}} Tools
        + $\LaTeX$
        + R with Sweave and knitr packages

+ Performing computations for 'Design of Experiments' problems
    + {{< fa screwdriver-wrench >}} Tools
        + C programming

+ Statistical Simulation (Bayesian Estimation, MCMC etc.)
    + {{< fa screwdriver-wrench >}} Tools
        + R Programming